version: '3.1'

services:
  paycap-client.e2e-tester:
    build:
      context: '../e2e'
    volumes:
      - '../e2e/src:/protractor/src'
      - '../artifacts/e2e/dist:/protractor/dist'
      - '../artifacts/reports/e2e:/protractor/reports'
      - '/dev/shm:/dev/shm'
    privileged: true
    network_mode: 'host'
