version: '3.1'

services:
  capitalhitelhaz.paycap-client.prod:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV
      - CI
    ports:
      - '9081:80'
